server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: access-management-service

# --- Security / Auth Service specific settings ---
auth:
  token:
    issuer: finxbridge-staging
  refresh-token:
    expiry: 604800000 # 7 days
