spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:http://localhost:8081}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: access-management-auth
          uri: lb://access-management-service
          predicates:
            - Path=/api/v1/access/auth/**
          filters:
            - StripPrefix=2

        - id: access-management-management
          uri: lb://access-management-service
          predicates:
            - Path=/api/v1/access/management/**
          filters:
            - StripPrefix=2
            - Authentication
            - RemoveRequestHeader=Content-Length

        - id: case-service
          uri: lb://case-service
          predicates:
            - Path=/api/v1/cases/**,/api/v1/campaigns/**,/api/v1/strategies/**
          filters:
            - StripPrefix=0
            - Authentication


        - id: notice-service
          uri: lb://notice-service
          predicates:
            - Path=/api/v1/notices/**
          filters:
            - StripPrefix=0
            - Authentication

        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/api/v1/communication/**
          filters:
            - StripPrefix=0
            - Authentication

        - id: template-service
          uri: lb://template-service
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - StripPrefix=0
            - Authentication

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - StripPrefix=0

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin\
        
      # Allow multipart file forwarding
      httpclient:
        wiretap: true
        response-timeout: 300s
        max-header-size: 16KB
 
      forwarded-headers-strategy: framework
 
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB



resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8081}

jwt:
  secret: ${JWT_SECRET:MySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds  