server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:https://staging.yourdomain.com}"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: access-management-auth
          uri: lb://access-management-service
          predicates:
            - Path=/api/v1/access/auth/**
          filters:
            - StripPrefix=2

        - id: access-management-management
          uri: lb://access-management-service
          predicates:
            - Path=/api/v1/access/management/**
          filters:
            - StripPrefix=2
            - Authentication
        
        - id: master-data-service
          uri: lb://master-data-service
          predicates:
            - Path=/api/v1/master-data/**
          filters:
            - StripPrefix=2
            - Authentication

        - id: case-sourcing-service
          uri: lb://case-sourcing-service
          predicates:
            - Path=/api/v1/case/**
          filters:
            - StripPrefix=2
            - Authentication
        
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/api/v1/communication/**
          filters:
            - StripPrefix=0
            - Authentication

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# --- Resilience4j ---
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

# --- JWT (shared secret) ---
jwt:
  secret: ${JWT_SECRET:MySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}
