server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: "configserver:http://config-server:8888/"

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:https://staging.yourdomain.com}
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

  application:
    name: api-gateway

# Rate limiting and basic gateway security placeholders
gateway:
  rate-limit:
    enabled: false
    requests-per-second: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
