spring:
  application:
    name: communication-service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    enabled: false

  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes
      cache-null-values: false

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
      template-service:
        connectTimeout: 5000
        readTimeout: 10000
  circuitbreaker:
    enabled: true

# NOTE: Third-party integration configurations (SMS, WhatsApp, Email, Payment, Dialer)
# are stored in Redis cache and retrieved from third_party_integration_master table
# No hardcoded credentials in application.yml for security

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


